module.exports = function () {
    return { 
        products: [
            { id: 1, purchase:"21-10-2018", name: "Introduction to Algorithms", category: "Computer Science", 
                description: "Book by Charles E. Leiserson, Clifford Stein, Ronald R ivest, and Thomas H. Cormen", publisher:"Arihant's",price: 5227,quantity:"10" },
            { id: 2, purchase:"21-10-2018", name: "Cracking the Coding Interview", category: "Computer Science", 
                description: "Book by Gayle Laakmann McDowell", price: 5228,quantity:"11"},
            { id: 3, purchase:"21-10-2018", name: "The C Programming Language", category: "Computer Science", 
                description: "Book by Brian Kernighan and Dennis Ritchie", price: 5228,quantity:"12" },
            
            { id: 4, purchase:"21-10-2018", name: "Elements of Electromagnetics", category: "ECE", 
                description: "Book by Matthew N.O. Sadiku", price: 8865,quantity:"15" },
            { id: 5, purchase:"21-10-2018",name: "FUNDAMENTALS OF DIGITAL CIRCUITS", category: "ECE", 
                description: "Book by A. ANAND KUMAR", price: 1024,quantity:"20" },
            { id: 6, purchase:"21-10-2018",name: "Digital Systems: Principles and Applications", category: "ECE", 
                description: "Book by Ronald J Tocci", 
                price: 6588,quantity:"5" },
            { id: 7, purchase:"21-10-2018",name: "Business Law, 6th Edition", category: "LAW", 
                description: "M.C. Kuchhal & Vivek Kuchhal", price: 8874,quantity:"7" },
            { id: 8, purchase:"21-10-2018",name: "International Law", category: "LAW", 
                description: "Malcolm D. Evans - 2014", price: 5647,quantity:"100" },
            { id: 8,purchase:"21-10-2018", name: "Rule of Law in India: A Quest for Reason", category: "LAW", 
                description: "Harish Narasappa - 2018", 
                price: 2314,quantity:"30" },
            { id: 10,purchase:"21-10-2018", name: "Project Management", category: "MANAGEMENT", 
                description: "K. Nagarajan - 2004 ", price: 2347,quantity:"27" },
            { id: 11, purchase:"21-10-2018",name: "Office Management", category: "MANAGEMENT", 
                description: "Balachandran - 2008", price: 3214,quantity:"22" },
			{ id: 12,purchase:"21-10-2018", name: "Essentials of Management", category: "MANAGEMENT", 
                description: "Harold Koontz - 2010", price: 2014,quantity:"56" },
            { id: 13, purchase:"21-10-2018",name: "Concepts of Physics", category: "PHYSICS", 
                description: "Textbook by H. C. Verma and Harish Chandra Verma", price: 2222,quantity:"44" },
            { id: 14,purchase:"21-10-2018", name: "The Feynman Lectures on Physics", category: "PHYSICS", 
                description: "Textbook by Matthew Sands, Richard Feynman, and Robert B. Leighton", price: 2668,quantity:"66" },
            { id: 15, purchase:"21-10-2018",name: "Fundamentals of Physics", category: "PHYSICS", 
                description: "Textbook by David Halliday, Jearl Walker, and Robert Resnick", price: 2022 ,quantity:"38"},
            { id: 16, purchase:"21-10-2018",name: "Vedic Mathematics", category: "MATHS", 
                description: "Book by Bharati Krishna Tirtha", price: 2357 ,quantity:"48"},
            { id: 17,purchase:"21-10-2018", name: "Advanced Engineering Mathematics", category: "MATHS", 
                description: "Textbook by Erwin Kreyszig", price: 8632,quantity:"80"},
            { id: 18,purchase:"21-10-2018", name: "The Math Book", category: "MATHS", 
                description: "Book by Clifford A. Pickover", price: 3225,quantity:"107" },
            { id: 18,purchase:"21-10-2018", name: "Theory of Machines", category: "MECHANICAL", 
                description: "Book by J.K. Gupta and R.S. Khurmi", price: 1478,quantity:"154" },
            { id: 20,purchase:"21-10-2018", name: "Machinery's Handbook", category: "MECHANICAL", 
                description: "Book by Erik Oberg and Franklin D. Jones", price: 8874 ,quantity:"6"},
            { id: 21,purchase:"21-10-2018", name: "Shigley's Mechanical Engineering Design", category: "MECHANICAL", 
                description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 8514 ,quantity:"75"},
            { id: 22, purchase:"21-10-2018",name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
                description: "Book by J.K. Gupta and R.S. Khurmi", price: 7536,quantity:"55" },
            { id: 23,purchase:"21-10-2018", name: "Civil Engineering Formulas", category: "CIVIL", 
                description: "Book by Tyler Gregory Hicks", price: 2222,quantity:"62" },
            { id: 24, purchase:"21-10-2018",name: "Theory of Structures", category: "CIVIL", 
                description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 3333,quantity:"23" },
            { id: 25, purchase:"21-10-2018",name: "Machinery's Handbook", category: "MECHANICAL", 
                description: "Book by Erik Oberg and Franklin D. Jones", price: 4588,quantity:"45" },
            { id: 26, purchase:"21-10-2018",name: "Shigley's Mechanical Engineering Design", category: "MECHANICAL", 
                description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 6666,quantity:"58" },
            { id: 27, purchase:"21-10-2018",name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
                description: "Book by J.K. Gupta and R.S. Khurmi", price: 8888,quantity:"225" },
            { id: 28, purchase:"21-10-2018",name: "Civil Engineering Formulas", category: "CIVIL", 
                description: "Book by Tyler Gregory Hicks", price: 8888 ,quantity:"38"},
            { id: 28,purchase:"21-10-2018", name: "Theory of Structures", category: "CIVIL", 
                description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 1100,quantity:"68" },
            { id: 30, purchase:"21-10-2018",name: "Machinery's Handbook", category: "MECHANICAL", 
                description: "Book by Erik Oberg and Franklin D. Jones", price: 5230,quantity:"41" },
            { id: 31,purchase:"21-10-2018", name: "Shigley's Mechanical Engineering Design", category: "MECHANICAL", 
                description: "Book by J. Keith Nisbett and Richard G. Budynas", price: 5241 ,quantity:"52"},
            { id: 32,purchase:"21-10-2018", name: "Civil Engineering: Conventional and Objective Type", category: "CIVIL", 
                description: "Book by J.K. Gupta and R.S. Khurmi", price: 5242,quantity:"63" },
            { id: 33,purchase:"21-10-2018", name: "Civil Engineering Formulas", category: "CIVIL", 
                description: "Book by Tyler Gregory Hicks", price: 5268 ,quantity:"40"},
            { id: 34,purchase:"21-10-2018", name: "Theory of Structures", category: "CIVIL", 
                description: "Book by Donovan Harold Young and Stephen Timoshenko", price: 4458,quantity:"88" },
           
        ],
        orders: []
    }
}
